services:
  - type: web
    name: ferrow-enhanced
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://ferrow-enhanced.onrender.com
      - key: DATABASE_URL
        value: postgresql://username:password@hostname:5432/database
    healthCheckPath: /api/health